Repository jahnavi23-web/gmeet_clone, pull requests merged in 2022-07, with the labels that each got.

#2 Add Barebones PeerJS API documentation
  server/docs/peerjs_doc.txt
Labels: documentation

#6 FIX: #5 Only a Single Connection for each PeerID
  server/public/index.html
  server/public/js/main.js
Labels: fix

#7 Add: Disconnect button to each new user connection
  server/public/css/style.css
  server/public/js/main.js
Labels: add
